### ISSUE TITLE
Please add Cloudian in the self validated table

### ISSUE THREAD

**Issue by hchu01** [github-technology-partners/ghes-storage-partners#9]
We have validated Cloudian HyperStore with GHES for versions:
3.5, 3.4, 3.3, 3.2, and 3.1

Link to our documentation is as follows:
Support: https://cloudian.com/support/
Documentation: https://cloudian.com/support/
Product Information: https://cloudian.com/products/hyperstore/

**Comment by mattlovestech** [comment]
@hchu01 Hi Henry, can you share a link to the docs? Looks like two links for support.

cc: @alexisabril

**Comment by hchu01** [comment]
@mattlovestech

For documentation, our manuals are available from inside the HyperStore product.  We do not have them in public accessible links.  Of course can also be available through support.  So support would be the best fit in this situation.

**Comment by mattlovestech** [comment]
thanks for clearing that up, I'll note that.

**Comment by mattlovestech** [comment]
@hchu01 I just opened a [PR](https://github.com/github-technology-partners/ghes-storage-partners/pull/10) for this thanks for providing the info.
